# Generated by Django 4.2 on 2023-04-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('onwifi', models.IntegerField()),
            ],
            options={
                'db_table': 'sensor_data',
                'db_table_comment': 'sensor data set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'user',
                'db_table_comment': 'users information',
                'managed': False,
            },
        ),
    ]
